name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and push Docker image"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          minikube update-context
          chmod 600 ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.15.4'

      - name: Helm Upgrade
        run: |
          helm upgrade --install go-web-app ./go-web-app \
            --set image.repository=alexanderlashov/go-web-app \
            --set image.tag=latest \
            --namespace default \
            --create-namespace

      - name: Wait for the service to be ready
        run: |
          kubectl rollout status deployment/go-web-app --namespace default

      - name: Verify the deployment with Minikube
        run: |
          minikube service go-web-app --namespace default --url
